### PR TITLE
Add dependency on guzzlehttp/psr7

### PR DESCRIPTION
**Pull request by tomcastleman**
# Fixes #

Since #689 the minimum version of `guzzlehttp/psr7` should be`^1.7.0` due to the use of [`GuzzleHttp\Psr7\Query`](https://github.com/guzzle/psr7/blob/master/src/Query.php).

However the dependency of `guzzlehttp/psr7` is currently only inferred through the dependency for [`guzzlehttp/guzzle:^6.3 || ^7.0`](https://github.com/twilio/twilio-php/blob/main/composer.json#L18).

Should `guzzlehttp/guzzle` resolve to version 6.5 (as at the time of writing), the inferred minimum version of `guzzlehttp/psr7` is only [`^1.6.1`](https://github.com/guzzle/guzzle/blob/6.5/composer.json#L28). In my case I had another dependency declaring `guzzle/psr7:<1.7` and so the issue did not become apparent during `composer update`, but only via a runtime exception in the app when the `Query` class was not found.

### Technical details:
* twilio-php version: 6.28.0
* php version: 8.0.9

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-php/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Guzzle maintainer here. It is not necessary to ask for 1.7.0. `^1.6 || ^2.0` is best, so long as you use the modern static class method API, rather than the legacy functions API. It was added in 1.6.0.

**Comment by GrahamCampbell** [comment]
If you wanna sure the versions installed are definitely PHP 8.1 compatible, you can use `^1.8.3 || ^2.1`.

**Comment by phpfui** [comment]
@tomcastleman Take the suggestion from @GrahamCampbell and update the psr7 dependency. This will help with 8.1 compatibility.  You will also have to remove the theseer/phpdox dependency, as it was removed after your branch was made.

I just got the other 8.1 fixes merged, so if you get this merged, then 8.1 will be fully supported. Then @shwetha-manvinkurke can merge and release an SDK fully supporting 8.1, which will be awesome for us cutting edge people.

**Comment by GrahamCampbell** [comment]
https://github.com/twilio/twilio-php/pull/776 replaces this PR.

**Pull request closed without merging**
