### PR TITLE
fix: Multipart support

### LINKED ISSUE #657: How to create a supporting document with a file?
# Issue Summary
I want to create a new supporting document with a file, but I can't find any way to attach the file.

### Code Snippet
```php
$twilioClient->numbers->v2->regulatoryCompliance->supportingDocuments->create(
    'Friendly name',
    'government_issued_document',
    ['address_sid' => 'ADxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'],
    // no way to attach the file
);
```

### PR DESCRIPTION
**Pull request by erickskrauch**
# Fixes #657

This PR adds support for the `multipart/form-data` to upload files. It also introduces the `File` entity to allow the HTTP client adapter to determine that request must be made as a multipart. The current implementation allows to upload file by file path, by resource obtained via `fopen` or by raw file contents. It also allows to use any other file contents format, supported by the specific HTTP adapter implementation (for example PSR-7 `StreamInterface` implementation for Guzzle).

The problem is that **Twilio's backend doesn't recognize file, uploaded with the `multipart/form-data`** :( I have tested my implementation with the different backend implementations and in every case I successfully managed to parse and store uploaded files. Twilio just don't recognize files. I already compared body formed by my implementation with a body formed with the raw `curl` command (see [this comments](https://github.com/twilio/twilio-php/issues/657#issuecomment-700620916)). I will gladly adjust body format to suit necessary Twilio's format if you will tip me how :)

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @erickskrauch,

Thanks for creating the PR! I am adding an internal identifier to track progress. We will update this ticket when we have a solution: DI-647

In the meantime, please see the [associated issue](https://github.com/twilio/twilio-php/issues/657#issuecomment-699234839) for the current workarounds.

Thank you!

With best regards,

Elmer

**Comment by erickskrauch** [comment]
@thinkingserious, thanks!

Any change to have a multipart fix on Twilio's backend side soon? I want to use this PR on the job's project to finish the task.

**Review by childish-sambino — COMMENTED** [review]
The Twilio backend does actually support file uploads, it's just that we use a different subdomain for this. The support document upload example [here](https://www.twilio.com/docs/phone-numbers/regulatory/api/supporting-documents?code-sample=code-create-a-supporting-document-and-upload-a-file&code-language=curl&code-sdk-version=default) uses _numbers-upload.twilio.com_ (instead of _numbers.twilio.com_).

We're currently investigating including such upload subdomains in this library, but it will mostly be generated code from an internal API definition schema.

Given all this, I'm inclined to review/approve the changes if all the regulatory-specific changes are reverted (since that particular API does not support file uploads, and it will be blown away on the next release anyway).

**Comment by erickskrauch** [comment]
@childish-sambino, hey, thanks a lot for a mention about the different domain. I didn't pay attention to it and didn't understand why my implementation doesn't work and the curl command works.

I removed all changes to the generated code as you requested. I also created a [separate branch where I made the necessary changes to support document uploading](https://github.com/erickskrauch/twilio-php/compare/dc7e31bda2b286904be671b386546d90a6f9f2cc...erickskrauch:regulatory_fast_fix). I checked my implementation: the document is uploaded successfully! I'm sure my solution isn't perfect, but it's more than enough to use in the job's project until the support of documents uploading will be included in the SDK.

**Comment by childish-sambino** [comment]
Moving this up the internal backlog. Should have a look to implement the upstream changes in a few sprints.

**Pull request merged**
