### PR TITLE
Options Builder interface for optional arguments.

### PR DESCRIPTION
**Pull request by ihumanable**
- Add the Options Builder Base Class
  - Adds Option Builders for all eligible actions
  - Fixes a naming bug with date time inequalities
  - Fixes a use resolution bug that over applied `Twilio\Serialize`

---

Rationale for change:

The initial idea for this change was raised in https://github.com/twilio/twilio-php/issues/305 (thanks to https://github.com/leandrolopes13, https://github.com/caponica, and https://github.com/apoca for their feedback.)

Optional arguments are handled in the `twilio-php` by accepting an associative array of optional keys and values to pass to the API.  This makes it easy to support all the optional parameters, but lessens developer ergonomics, since it doesn't provide any inline documentation or autocomplete for optional arguments.

This change introduces new Options builders that support 2 new ways for specifying optional arguments that provide better usability.

```php
<?php

use Twilio\Values;
use Twilio\Rest\Client;
use Twilio\Rest\Api\V2010\Account\CallOptions;

$client = new Client();

// Original Way (5.0.x)
$client->calls->create(
    '+14155551234',
    '+14155557890',
    array(
        'applicationSid' => 'AP123',
        'method' => 'POST',
    )
);

// Options Factory
$client->calls->create(
    '+14155551234',
    '+14155557890',
    CallOptions::create(
        Values::NONE,
        'AP123',
        'POST'
    )
);

// Options Builder
$client->calls->create(
    '+14155551234',
    '+14155557890',
    CallOptions::create()->setApplicationSid('AP123')
                         ->setMethod('POST')
);
```

The `Options Factory` provides fully documented optional arguments for every optional argument supported by the Resource's Action.  This is a fast way to handle endpoints that have a few optional arguments.

The `Options Builder` provides fully documented setters for every optional arguments, this is great for actions that support a large number of optional arguments, so that you don't need to provided tons of default values.

Both of these options work well with autocompleting IDEs.

### CODE REVIEW

**Comment by caponica** [comment]
From a very quick scan, this looks great! Thanks for all the hard work making this happen.

**Comment by dprothero** [comment]
LGTM

**Comment by jingming** [comment]
👍

**Comment by ihumanable** [comment]
@caponica @dprothero @jingming Thank you for your review and feedback, this PR will be included for immediate release as twilio-php `5.1.0`

**Pull request merged**
