### PR TITLE
Fix: Php 8.1 support

### PR DESCRIPTION
**Pull request by phpfui**
# Fixes #

* Adds #[\ReturnTypeWillChange] where needed (according to unit tests).
* Fixes a null parameter warning passed to trim in Version.
* Updates PHPUnit to V7, but housekeeping only, as composer does the right thing normally.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-php/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by petewalker** [comment]
This resolves #709 and #712 - @JenniferMah / @shwetha-manvinkurke any chance this could be looked at?

**Comment by petewalker** [comment]
@shwetha-manvinkurke Thanks for running the CI! Could this be merged?

**Review by thomaspicquet — APPROVED** [review]

**Comment by thomaspicquet** [comment]
Would be great if it was merged, thank you @phpfui for the hard work!

**Comment by phpfui** [comment]
Happy to help!

**Comment by phpfui** [comment]
Will have till wait till Monday. Skiing!

**Comment by phpfui** [comment]
This should now be good to merge.  All tests run my Windows machine. I fixed a merge mistake from my merge with the web interface.

**Review by shwetha-manvinkurke — APPROVED** [review]

**Comment by thomaspicquet** [comment]
thanks @phpfui! looking forward to the new tag release.

**Pull request merged**
