### PR TITLE
fix: Eliminate typo in README.md

### PR DESCRIPTION
**Pull request by ahmedghanem00**
# Fixes #

Fixing a typo in README.me file

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-php/blob/main/CONTRIBUTING.md) and my PR follows them
- [ ] I have titled the PR appropriately
- [ ] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Review by AsabuHere — APPROVED** [review]
LGTM!

**Comment by ahmedghanem00** [comment]
@AsabuHere Hi there, Is there any schedule to get this merged ?

**Comment by stevebauman** [comment]
Any merge on this? It's literally just two lines in the docs

**Comment by ahmedghanem00** [comment]
Pinging @sbansla @tiwarishubham635, As you have been taking on the recent merged PRs here.

**Comment by tiwarishubham635** [comment]
> Pinging @sbansla @tiwarishubham635 @AsabuHere, As you have been taking on the recent merged PRs here.

Done

**Comment by ahmedghanem00** [comment]
Finally 😅, Thanks

**Pull request merged**
